<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>EventHub</RootNamespace>
      <UserSecretsId>bec8c2c0-cd8f-4676-812f-e1fab2c7fbc1</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\EventHub.Core\EventHub.Core.csproj" />
      <ProjectReference Include="..\EventHub.Infrastructure\EventHub.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="StackExchange.Redis" Version="3.1.13" />
    </ItemGroup>

</Project>
